---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

# Files to ignore can be added to pre-commit config
# ignore: |
#   hack/crds/*
#   config/**
#   bundle/**

rules:
  comments:
    min-spaces-from-content: 1
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
  new-lines:
    type: platform
